package model

data class Status(
    var index: Int = 0,
    var timestamp: Int = 0,
    var noOfTransmission: Int = 0,
    var noOfFailedTransmission: Int = 0,
    var noOfAttachment: Int = 0,
    var noOfDisattachment: Int = 0,
    var noOfSimError: Int = 0,
    var latency_ms: Int = 0,
    var avgLatency_ms: Int = 0,
    var minLatency_ms: Int = 0,
    var maxLatency_ms: Int = 0,
    var pingLatency_ms: Int = 0,
    var avgPingLatency_ms: Int = 0,
    var minPingLatency_ms: Int = 0,
    var maxPingLatency_ms: Int = 0,
    var rsrp: Int = 0,
    var avgRsrp: Int = 0,
    var minRsrp: Int = 0,
    var maxRsrp: Int = 0,
    var rssi: Int = 0,
    var avgRssi: Int = 0,
    var minRssi: Int = 0,
    var maxRssi: Int = 0,
    var sinr: Int = 0,
    var avgSinr: Int = 0,
    var minSinr: Int = 0,
    var maxSinr: Int = 0,
    var rsrq: Int = 0,
    var avgRsrq: Int = 0,
    var minRsrq: Int = 0,
    var maxRsrq: Int = 0,
    var txPower: Int = 0,
    var avgTxPower: Int = 0,
    var minTxPower: Int = 0,
    var maxTxPower: Int = 0,
    var ceMode: Int = 0,
    var ecl: Int = 0,
    var batteryVoltage_mV: Int = 0,
) {
    constructor(intDataType: Int) : this() // for jackson translation
}